name: YuvanBank Regression UI Tests (Sauce Labs)

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome] # running only chrome per your command

    env:
      # 🔐 Sauce credentials
      SAUCE_USERNAME: ${{ secrets.SAUCE_UNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_KEY }}

      # 🧪 DriverFactory / pytest parameters
      REMOTE_DRIVER: sauce
      SAUCE_PLATFORM: Windows 11
      SAUCE_VERSION: latest
      SAUCE_REGION: eu
      SAUCE_BUILD: "${{ github.ref_name }} #${{ github.run_number }}"
      SAUCE_NAME: "PyTest-${{ matrix.browser }} @ ${{ github.sha }}"
      SAUCE_TAGS: "pytest,gha"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -U pytest selenium pytest-xdist allure-pytest python-dotenv

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Verify Sauce credentials
        run: |
          test -n "${SAUCE_USERNAME}" || (echo "❌ SAUCE_USERNAME missing"; exit 1)
          test -n "${SAUCE_ACCESS_KEY}" || (echo "❌ SAUCE_ACCESS_KEY missing"; exit 1)
          echo "✅ Sauce credentials available"

      - name: Run Register Test on Sauce Labs (EU region)
        run: |
          mkdir -p reports allure-results
          pytest -v tests/test_register.py \
            --remote \
            --cloud saucelabs \
            --browser chrome \
            --headless \
            --sauce-region eu \
            --junitxml=reports/junit-chrome.xml

      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-chrome
          path: reports/*.xml

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-chrome
          path: allure-results
          if-no-files-found: ignore
